<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Exceptions\Typed\**" />
    <EmbeddedResource Remove="Exceptions\Typed\**" />
    <EmbeddedResource Remove="Generators\**" />
    <None Remove="Exceptions\Typed\**" />
    <None Remove="Generators\**" />
  </ItemGroup>

</Project>
